# https://docs.readthedocs.io/en/stable/config-file/v2.html
version: 2
build:
  os: ubuntu-22.04
  tools:
    python: '3.12'
sphinx:
  configuration: docs/conf.py
formats:
  - pdf
  - epub
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
